Fix GoogleChrome Checksums
Getting the following error on endpoints trying to install the latest version of chrome.

```
ERROR: Checksum for 'D:\Users\kam-qa\AppData\Local\Temp\chocolatey\GoogleChrome\110.0.5481.97\googlec
hromestandaloneenterprise64.msi' did not meet '68616f6440cf26c8236fbd2434d0c77af1a8a7d463103b323a949c
c87206ed2d' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum
 --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --igno
re-checksums if necessary.
The upgrade of googlechrome was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\GoogleChrome\tools\chocolateyInstall.ps1'.
 See log for details.
```

This works:

```
PS D:\Users\kam-qa\Desktop\it-chef> choco upgrade googlechrome -yf --checksum64 983287A6BEADBF368DD15
43BCB3EDFA917B9827406FE760B79A609FEBA12AEA8
Chocolatey v1.2.0
Upgrading the following packages:
googlechrome
By upgrading, you accept licenses for the packages.

You have GoogleChrome v110.0.5481.78 installed. Version 110.0.5481.97 is available based on your sour
ce(s).
Progress: Downloading GoogleChrome 110.0.5481.97... 100%

GoogleChrome v110.0.5481.97 (forced) [Approved]
googlechrome package files upgrade completed. Performing other installation steps.
Using system proxy server 'vpce-08e4678df16ae8396-sf6iyll4.vpce-svc-02cbc839d79d8ab71.us-west-2.vpce.
amazonaws.com:4751'.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be
 redownloaded.
Hashes match.
Hashes match.
Installing googlechrome...
googlechrome has been installed.
  googlechrome may be able to be automatically uninstalled.
 The upgrade of googlechrome was successful.
  Software installed as 'MSI', install location is likely default.

Chocolatey upgraded 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

Downloaded the packages from the url and retrieved the checksums.